### ISSUE TITLE
Group functions in reference?

### ISSUE THREAD

**Issue by maelle** [ropensci/stplanr#295]
Now that I've spent quite some time staring at your website :wink: I'd suggest adding grouping to the reference section, because at the moment it only shows all functions by alphabetical order.

Here's the dev_guide's guidance on the matter: https://ropensci.github.io/dev_guide/building.html#function-grouping We recommend using the `roxygen2` `@family` tag that gives grouping in the man pages, and allows to use the `pkgdown` `has_concept` in the `pkgdown` config file so your config file should have lines like

```yaml
reference:
- title: Helpers
  contents:
  - has_concept("helper")
- title: Finance
  contents:
- has_concept("finance")
```

where `finance`, `helper` are used in .R files in function docs `#' @family finance`.
